services:
  driver:
    build:
      context: .
      dockerfile: docker/driver/Dockerfile
      args:
        BUILDPLATFORM: linux/arm64
    network_mode: host
    platform: linux/arm64
    env_file:
      - ./docker/.env
    environment:
      - CYCLONEDDS_URI=file:///dds/cyclonedds_robot.xml
    volumes:
      - ./dds/cyclonedds_robot.xml:/dds/cyclonedds_robot.xml
      - /dev:/dev  
      - ./ros2_ws/src/j2cdynamics_bringup:/ros2_ws/src/j2cdynamics_bringup
      - ./ros2_ws/src/j2cdynamics_driver:/ros2_ws/src/j2cdynamics_driver
      - ./ros2_ws/src/j2cdynamics_diagnostics:/ros2_ws/src/j2cdynamics_diagnostics
      - ./ros2_ws/src/do_description:/ros2_ws/src/do_description
    devices:
      - /dev/serial:/dev/serial
    group_add:
      - "dialout"
    privileged: true
    command: ros2 launch j2cdynamics_bringup driver.launch.py
    
    healthcheck:
      test: [
        "CMD-SHELL",
        ". /opt/ros/humble/setup.sh && ros2 topic list | grep -q '^/odom$'"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  camera:
    build:
      context: .
      dockerfile: docker/camera/Dockerfile
    platform: linux/arm64
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - ./docker/.env
    environment:
      - CYCLONEDDS_URI=file:///dds/cyclonedds_robot.xml
      - HOME=/tmp
      - UDEV=1
    volumes:
      - ./dds/cyclonedds_robot.xml:/dds/cyclonedds_robot.xml
      - /dev:/dev  
      - /run/udev:/run/udev:ro
      - ./ros2_ws/src/j2cdynamics_bringup:/ros2_ws/src/j2cdynamics_bringup
      - ./ros2_ws/src/j2cdynamics_camera:/ros2_ws/src/j2cdynamics_camera
      - ./camera/model/best_int8.onnx:/ros2_ws/model/best_int8.onnx
    group_add:
      - "video"
    depends_on:
      driver:
        condition: service_healthy
    command: ros2 launch j2cdynamics_bringup camera.launch.py

  lidar: 
    build:
      context: .
      dockerfile: docker/lidar/Dockerfile
    platform: linux/arm64
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - ./docker/.env
    environment:
      - CYCLONEDDS_URI=file:///dds/cyclonedds_robot.xml
    volumes:
      - ./dds/cyclonedds_robot.xml:/dds/cyclonedds_robot.xml
      - /dev:/dev  
    command: ros2 launch j2cdynamics_bringup lidar.launch.py
    healthcheck:
      test:
        [
          "CMD-SHELL",
          ". /opt/ros/humble/setup.sh && ros2 topic list | grep -q '^/scan$'"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  navigation:
    build:
      context: .
      dockerfile: docker/navigation/Dockerfile
    platform: linux/arm64
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - ./docker/.env
    environment:
      - CYCLONEDDS_URI=file:///dds/cyclonedds_robot.xml
    volumes:
      - ./dds/cyclonedds_robot.xml:/dds/cyclonedds_robot.xml
      - /dev:/dev
      - ./ros2_ws/src/j2cdynamics_bringup:/ros2_ws/src/j2cdynamics_bringup
      - ./ros2_ws/src/j2cdynamics_bringup/maps:/maps
    devices:
      - /dev/input/js0:/dev/input/js0
    depends_on:
      lidar:
        condition: service_healthy
      driver:
        condition: service_healthy
    command: ros2 launch j2cdynamics_bringup do_robot.launch.py use_teleop:=true mode:=localization  map:=/maps/arena/map
    healthcheck:
      test:
        [
          "CMD-SHELL",
          ". /opt/ros/humble/setup.sh && \
          ros2 service call /lifecycle_manager_navigation/is_active std_srvs/srv/Trigger {} | grep -q 'success=True'"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  
  mission:
    build:
      context: .
      dockerfile: docker/navigation/Dockerfile
    platform: linux/arm64
    network_mode: host
    privileged: true
    env_file:
      - ./docker/.env
    environment:
      - CYCLONEDDS_URI=file:///dds/cyclonedds_robot.xml
    volumes:
      - ./dds/cyclonedds_robot.xml:/dds/cyclonedds_robot.xml
      - ./ros2_ws/src/j2cdynamics_bringup:/ros2_ws/src/j2cdynamics_bringup
      - ./ros2_ws/src/j2cdynamics_mission:/ros2_ws/src/j2cdynamics_mission
    depends_on:
      navigation:
        condition: service_healthy
    command: ros2 launch j2cdynamics_bringup mission.launch.py 

  simulation:
    build: 
      context: .
      dockerfile: simulation/docker/Dockerfile
    platform: linux/amd64
    volumes:
      - ./ros2_ws:/home/ubuntu/ros2_ws
    ports:
      - "6080:80"
    shm_size: 512m
    security_opt:
      - seccomp=unconfined

