services:
  ros2-robot:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: robot
      args:
        BUILDPLATFORM: linux/arm64
    network_mode: host
    platform: linux/arm64
    env_file:
      - ./docker/.env
    environment:
      - CYCLONEDDS_URI=file:///dds/cyclonedds_robot.xml
    volumes:
      - ./ros2_ws/src:/ros2_ws/src
      - ./dds/cyclonedds_robot.xml:/dds/cyclonedds_robot.xml
      - /dev:/dev  
    command: >
      bash -c "
        ros2 run arduino_controller arduino_bridge
      "
    group_add:
      - "dialout"
    privileged: true