services:
  ros2-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    network_mode: host
    privileged: true
    env_file:
      - ./docker/.env
    environment: 
      -  CYCLONEDDS_URI=file:///dds/cyclonedds_dev.xml
    volumes:
      - ./ros2_ws/src:/ros2_ws/src
      - ./dds/cyclonedds_dev.xml:/dds/cyclonedds_dev.xml
    stdin_open: true
    tty: true
