version: '3'
services:
  ros2-dev:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    network_mode: host
    env_file:
      - .env
    environment: 
      -  CYCLONEDDS_URI=file:///dds/cyclonedds_mac.xml
    volumes:
      - ./ros2_ws:/ros2_ws
      - ./dds/cyclonedds_mac.xml:/dds/cyclonedds_mac.xml
    stdin_open: true
    tty: true