; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; =========================
; Base environment
; =========================
[env]
platform = atmelavr
board = megaatmega2560
framework = arduino

lib_deps = 
	waspinator/AccelStepper@^1.64

; =========================
; Base robot configuration
; =========================
[robot-base]
build_src_filter = 
	+<common/> 
	+<${PIOENV}/>
build_flags =
    -Isrc/${PIOENV}
    -Isrc/common

; =========================
; D-O robot firmware
; =========================
[env:do]
extends = robot-base
build_src_filter =
    ${robot-base.build_src_filter}
    +<do/>

; =========================
; D-O2 robot firmware
; =========================
[env:do2]
extends = robot-base
build_src_filter =
    ${robot-base.build_src_filter}
    +<do2/>

; =========================
; Base test configuration
; =========================
[test-base]
build_src_filter = 
	+<common/> 
	+<${PIOENV}/>
build_flags =
    -Isrc/${PIOENV}
    -Isrc/common

; =========================
; Stepper test
; =========================
[env:test-stepper]
extends = test-base

; =========================
; DC motor test
; =========================
[env:test-dc-motor]
extends = test-base
build_src_filter =
    ${test-base.build_src_filter}
    +<do2/drivers>
    +<do2/do2_config.hpp>
